//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.24 at 11:43:14 AM TRT 
//


package com.hoaxify.backend.wsclient.participant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Banka", propOrder = {
    "code",
    "name",
    "bIlAd",
    "adr"
})
public class Bank {

    @XmlElement(name = "bKd", required = true)
    protected String code;
    @XmlElement(name = "bAd", required = true)
    protected String name;
    @XmlElement(required = true)
    protected String bIlAd;
    @XmlElement(required = true)
    protected String adr;
    @XmlAttribute(name = "sonIslemTuru")
    protected String sonIslemTuru;
    @XmlAttribute(name = "sonIslemZamani")
    protected String sonIslemZamani;

    /**
     * Gets the value of the bKd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBKd() {
        return code;
    }

    /**
     * Sets the value of the bKd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBKd(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the bAd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAd() {
        return name;
    }

    /**
     * Sets the value of the bAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAd(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bIlAd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIlAd() {
        return bIlAd;
    }

    /**
     * Sets the value of the bIlAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIlAd(String value) {
        this.bIlAd = value;
    }

    /**
     * Gets the value of the adr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdr() {
        return adr;
    }

    /**
     * Sets the value of the adr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr(String value) {
        this.adr = value;
    }

    /**
     * Gets the value of the sonIslemTuru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonIslemTuru() {
        return sonIslemTuru;
    }

    /**
     * Sets the value of the sonIslemTuru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonIslemTuru(String value) {
        this.sonIslemTuru = value;
    }

    /**
     * Gets the value of the sonIslemZamani property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonIslemZamani() {
        return sonIslemZamani;
    }

    /**
     * Sets the value of the sonIslemZamani property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonIslemZamani(String value) {
        this.sonIslemZamani = value;
    }

}
