//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.24 at 11:43:14 AM TRT 
//


package com.hoaxify.backend.wsclient.participant.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hoaxify.backend.wsclient.participant.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public BankaSubeOkuIstem createBankaSubeOkuIstem() {
        return new BankaSubeOkuIstem();
    }

    public BankaSubeOkuCevap createBankaSubeOkuCevap() {
        return new BankaSubeOkuCevap();
    }

    public BLSCvp createBLSCvp() {
        return new BLSCvp();
    }

    public BNKCvp createBNKCvp() {
        return new BNKCvp();
    }

    public SUBCvp createSUBCvp() {
        return new SUBCvp();
    }
    public BSBCvp createBSBCvp() {
        return new BSBCvp();
    }

    public TUMCvp createTUMCvp() {
        return new TUMCvp();
    }

    public SGBCvp createSGBCvp() {
        return new SGBCvp();
    }

    public SGSCvp createSGSCvp() {
        return new SGSCvp();
    }

    public HataSonuc createHataSonuc() {
        return new HataSonuc();
    }

    public Bank createBanka() {
        return new Bank();
    }

    public Sube createSube() {
        return new Sube();
    }

    public BankaSubeleri createBankaSubeleri() {
        return new BankaSubeleri();
    }

}
