//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.24 at 11:43:14 AM TRT 
//


package com.hoaxify.backend.wsclient.participant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SGBCvp", propOrder = {
    "bank",
    "sgbYok"
})
public class SGBCvp {

    protected List<Bank> bank;
    @XmlElement(name = "SGBYok")
    protected Object sgbYok;

    /**
     * Gets the value of the banka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the banka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBanka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bank }
     * 
     * 
     */
    public List<Bank> getBanka() {
        if (bank == null) {
            bank = new ArrayList<Bank>();
        }
        return this.bank;
    }

    /**
     * Gets the value of the sgbYok property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSGBYok() {
        return sgbYok;
    }

    /**
     * Sets the value of the sgbYok property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSGBYok(Object value) {
        this.sgbYok = value;
    }

}
