//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.24 at 11:43:14 AM TRT 
//


package com.hoaxify.backend.wsclient.participant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SGSCvp", propOrder = {
    "sube",
    "sgsYok"
})
public class SGSCvp {

    protected List<Sube> sube;
    @XmlElement(name = "SGSYok")
    protected Object sgsYok;

    /**
     * Gets the value of the sube property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sube property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSube().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sube }
     * 
     * 
     */
    public List<Sube> getSube() {
        if (sube == null) {
            sube = new ArrayList<Sube>();
        }
        return this.sube;
    }

    /**
     * Gets the value of the sgsYok property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSGSYok() {
        return sgsYok;
    }

    /**
     * Sets the value of the sgsYok property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSGSYok(Object value) {
        this.sgsYok = value;
    }

}
