//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.24 at 11:43:14 AM TRT 
//


package com.hoaxify.backend.wsclient.participant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SUBCvp", propOrder = {
    "sube"
})
public class SUBCvp {

    @XmlElement(required = true)
    protected Sube sube;

    /**
     * Gets the value of the sube property.
     * 
     * @return
     *     possible object is
     *     {@link Sube }
     *     
     */
    public Sube getSube() {
        return sube;
    }

    /**
     * Sets the value of the sube property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sube }
     *     
     */
    public void setSube(Sube value) {
        this.sube = value;
    }

}
