//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.24 at 11:43:14 AM TRT 
//


package com.hoaxify.backend.soapclient.participant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="blgTur" type="{http://bs.tcmb.gov.tr/services/bankaSubeOku/}BilgiTuru"/&gt;
 *         &lt;element name="bKd" type="{http://bs.tcmb.gov.tr/services/bankaSubeOku/}BankaKodu" minOccurs="0"/&gt;
 *         &lt;element name="sKd" type="{http://bs.tcmb.gov.tr/services/bankaSubeOku/}SubeKodu" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blgTur",
    "bKd",
    "sKd"
})
@XmlRootElement(name = "bankaSubeOkuIstem")
public class BankaSubeOkuIstem {

    @XmlElement(required = true)
    protected String blgTur;
    protected String bKd;
    protected String sKd;

    /**
     * Gets the value of the blgTur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlgTur() {
        return blgTur;
    }

    /**
     * Sets the value of the blgTur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlgTur(String value) {
        this.blgTur = value;
    }

    /**
     * Gets the value of the bKd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBKd() {
        return bKd;
    }

    /**
     * Sets the value of the bKd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBKd(String value) {
        this.bKd = value;
    }

    /**
     * Gets the value of the sKd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKd() {
        return sKd;
    }

    /**
     * Sets the value of the sKd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKd(String value) {
        this.sKd = value;
    }

}
